### ISSUE TITLE
licensing/releasing onto crates.io

### ISSUE THREAD

**Issue by vidhanio** [crescentrose/sourcon#3]
Hi there!

I found this library super useful, and was wondering if it would be possible for you to add it to crates.io and license it for use in projects. :)

**Comment by crescentrose** [comment]
Hey! Thanks for taking a look at this. This was a toy project, and I don't really have much of a use case for it currently. But I can definitely add a license and release it to crates.io. I'll add a license now so that you are safe to use it, and I'll deploy it to crates.io sometime this week after updating the dependencies, as I have quite a busy week at my day job :)

**Comment by vidhanio** [comment]
thank you so much! i appreciate the response. :)

**Comment by crescentrose** [comment]
Hey! Thanks for waiting. It should be available now: https://crates.io/crates/sourcon

At some point I will likely come back to this project, clean up the code a bit, add some tests and make it nicer to work with. But I am not sure when will that exactly be. If you need something please let me know. In the meantime I'll close this :)

**Comment by vidhanio** [comment]
thanks! will do :)
